# Please remove the Testing entry for all non-demo usages!
# Please also review and adjust handler.yaml as there are
# HARDCODED PASSWORDS for testing and other wildcard which are not
# suitable for production use!

# Allows Anonymous Login (also from the WebUI!)
Anonymous:
    label: Anonymous
    description: Access for as guests without credentials
    handler: Anonymous
    type: anon

# Test Accounts with hardcoded passwords and userinfo in handler.yaml
Administration:
    label: Administration
    description: |
        Administration accounts - valid user names are <tt>caop</tt> (CA operator), <tt>raop</tt> (RA operator).<br>
        Password for all accounts is <tt>openxpki</tt> on <b>unmodified config checkouts</b>,<br>
        package installers set a <b>random value</b> that can be found in the file auth/handler.yaml.
    handler: Administration
    type: passwd

# The default handler for automated interfaces, hidden from the UI
_System:
    handler: System